/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Memories
         * @description Filter, search and sort memories (any status/sensitivity).
         *
         *     Body is a ``MemoryFilter``; an empty ``{}`` returns everything with the
         *     default ordering. This is the admin read path — do not expose publicly.
         */
        post: operations["search_memories_memories_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Memory
         * @description Create a single memory directly as 'active' (no review step).
         */
        post: operations["commit_memory_memories_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Memories
         * @description Approve or reject candidates; approving a `supersedes` candidate swaps atomically.
         */
        post: operations["review_memories_memories_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Facets
         * @description Filter options for the UI: status/sensitivity (from schema) + distinct category/type/source.
         */
        get: operations["get_facets_memories_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory
         * @description Fetch one memory by id, in ANY status/sensitivity. Missing id -> 400.
         */
        get: operations["get_memory_memories__id__get"];
        put?: never;
        post?: never;
        /**
         * Purge Memory
         * @description Permanently delete one memory — row and search index.
         *
         *     Rejecting or superseding only changes a status; the text stays. This is the
         *     only way to actually remove content, e.g. when something was captured that
         *     shouldn't have been. Not reachable over MCP — deleting is the human's call.
         */
        delete: operations["purge_memory_memories__id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Memory
         * @description Edit fields of one memory in place — partial, only the fields sent apply.
         *
         *     A missing id raises a StoreError -> 400. Setting `supersedes` on an active
         *     memory retires the old target (the store performs the swap).
         */
        patch: operations["update_memory_memories__id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Decision
         * @description One review decision for a candidate memory.
         */
        Decision: {
            /**
             * Id
             * @description The id of the candidate memory.
             */
            id: number;
            /**
             * Approve
             * @description Whether to approve this memory.
             */
            approve: boolean;
            /**
             * Reason
             * @description If rejected, why?
             */
            reason?: string | null;
        };
        /**
         * Facets
         * @description Filter dropdown options (response shape of `facets()` for the API).
         */
        Facets: {
            /** Status */
            status: string[];
            /** Sensitivity */
            sensitivity: string[];
            /** Category */
            category: string[];
            /** Type */
            type: string[];
            /** Source */
            source: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Memory
         * @description A stored memory row — the web API's response shape (and OpenAPI schema).
         *
         *     The store functions return plain dicts; FastAPI validates/serializes them
         *     against this model via the endpoints' return annotations. That is what gives
         *     `/docs` a full schema and lets the frontend generate its types from it.
         */
        Memory: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Tags */
            tags: string;
            /** Confidence */
            confidence: number;
            /**
             * Sensitivity
             * @enum {string}
             */
            sensitivity: "public" | "normal" | "private" | "sensitive" | "secret";
            /**
             * Status
             * @enum {string}
             */
            status: "candidate" | "active" | "superseded" | "rejected";
            /** Source */
            source: string;
            /** Supersedes */
            supersedes: number | null;
            /** Reason */
            reason: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
        };
        /**
         * MemoryFilter
         * @description Filter, sort and paginate memories for the web-UI / admin read path.
         *
         *     Consumed by ``list_memories``. Every SQL identifier (the ``choices`` keys,
         *     the ``timestamps`` keys and ``order_by``) comes from a ``Literal`` allowlist
         *     so it can be inlined into the query safely; all actual values are passed as
         *     bound parameters.
         */
        MemoryFilter: {
            /**
             * Choices
             * @description Per-column allowlist filters, each applied as `<col> IN (...)`. Empty value lists are ignored. Example: {'status': ['candidate'], 'category': ['work', 'hardware']}.
             */
            choices?: {
                [key: string]: string[];
            };
            /**
             * Search
             * @description Free text; matched as LIKE '%…%' over title, body and tags.
             */
            search?: string | null;
            /**
             * Timestamps
             * @description Timestamp comparisons. Each value is an operator directly followed by 'YYYY-MM-DD HH:MM:SS'; operator is one of >=, <=, =, >, <. Example: {'created_at': '>=2023-01-01 00:00:00'}.
             */
            timestamps?: {
                [key: string]: string;
            };
            /**
             * Order By
             * @description Column to sort by.
             * @default created_at
             * @enum {string}
             */
            order_by?: "created_at" | "updated_at" | "title" | "confidence" | "type" | "sensitivity" | "status" | "source" | "valid_from" | "valid_to" | "supersedes" | "tags";
            /**
             * Descending
             * @description Sort descending (newest / highest first).
             * @default true
             */
            descending?: boolean;
        };
        /**
         * MemoryInput
         * @description One memory to propose. Only ``title`` and ``body`` are required.
         *
         *     Set ``supersedes`` to the id of an existing active memory when this one is
         *     meant to replace it; the actual swap happens at approval time, not on
         *     suggestion.
         */
        MemoryInput: {
            /**
             * Title
             * @description Short, descriptive title. Write in English.
             */
            title: string;
            /**
             * Body
             * @description The actual memory content. Always write it in English, regardless of the conversation language, so it stays consistently searchable.
             */
            body: string;
            /**
             * Type
             * @description preference | fact | goal | project | environment
             * @default note
             */
            type?: string;
            /**
             * Category
             * @description communication | work | tech_stack | hardware | …
             * @default general
             */
            category?: string;
            /**
             * Tags
             * @description Free-text extra search terms, in English.
             * @default
             */
            tags?: string;
            /**
             * Confidence
             * @description How confident are you in this fact? 0.0–1.0 (1.0 = 100%).
             * @default 1
             */
            confidence?: number;
            /**
             * Sensitivity
             * @description public | normal | private | sensitive | secret. 'sensitive'/'secret' are stored but never returned by the read tools — they are viewable only in the web UI.
             * @default normal
             * @enum {string}
             */
            sensitivity?: "public" | "normal" | "private" | "sensitive" | "secret";
            /**
             * Source
             * @description Where the information came from
             * @default chat
             */
            source?: string;
            /**
             * Valid From
             * @description YYYY-MM-DD HH:MM:SS, from when this memory is valid. Defaults to now.
             */
            valid_from?: string | null;
            /**
             * Valid To
             * @description YYYY-MM-DD HH:MM:SS, until when this memory is valid. Defaults to always.
             */
            valid_to?: string | null;
            /**
             * Supersedes
             * @description Replace this memory by the one with this id.
             */
            supersedes?: number | null;
        };
        /**
         * MemoryUpdate
         * @description Partial edit for PATCH /memories/:id — every field optional, only the
         *     ones sent are applied. Mirrors the editable set; status / source / timestamps
         *     stay read-only (status changes via review).
         */
        MemoryUpdate: {
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Tags */
            tags?: string | null;
            /** Category */
            category?: string | null;
            /** Type */
            type?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Sensitivity */
            sensitivity?: ("public" | "normal" | "private" | "sensitive" | "secret") | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Supersedes */
            supersedes?: number | null;
        };
        /**
         * PurgeResult
         * @description What `purge_mem` removed — the deleted row, plus how many memories had
         *     their `supersedes` pointer cleared because it referenced it.
         */
        PurgeResult: {
            deleted: components["schemas"]["Memory"];
            /** Supersedes Cleared */
            supersedes_cleared: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_memories_memories_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryFilter"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_memory_memories_commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_memories_memories_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facets_memories_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
        };
    };
    get_memory_memories__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_memory_memories__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_memories__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
